"""removed monthly

Revision ID: 13cd291cecf8
Revises: 649e39d97d16
Create Date: 2025-02-25 22:56:36.394924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13cd291cecf8'
down_revision = '649e39d97d16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_column('monthly')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monthly', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
