"""added monthly boolean to appointments

Revision ID: 649e39d97d16
Revises: b3209a9e1417
Create Date: 2025-02-25 22:45:49.472231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '649e39d97d16'
down_revision = 'b3209a9e1417'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monthly', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_column('monthly')

    # ### end Alembic commands ###
